version: "3.9"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: tsdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: aipass
      POSTGRES_DB: aidb
    ports: ["5432:5432"]
    volumes:
      - tsdb_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nats:
    image: nats:2.10
    container_name: nats
    restart: unless-stopped
    ports: ["4222:4222","8222:8222"]
    command: ["--http_port","8222"]

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports: ["6379:6379"]
    volumes: ["redis_data:/data"]

volumes:
  tsdb_data:
  redis_data:
